name: On new branch to main

on:
  create

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
  WORKING_DIR: '07module/web-demo2'

jobs:
  new-branch-to-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Validate terraform fmt
        run: terraform fmt -check
        working-directory: ${{ env.WORKING_DIR }}

      - name: Validate Terraform code
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}

  tfsec:
    needs: new-branch-to-validate
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: tfsec
        # You may pin to the exact commit or the version.
        # uses: aquasecurity/tfsec-action@b466648d6e39e7c75324f25d83891162a721f2d6
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          # Directory to run the action on, from the repo root. Default is . (root of the repository)
          working_directory: ${{ env.WORKING_DIR }}
          github_token: ${{ env.GITHUB_TOKEN }}


  create-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    needs: [new-branch-to-validate, tfsec]  # Ensure this job runs only if the previous jobs succeed
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Current Branch Name
        id: get-branch-name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Automated PR: Merge ${{ steps.get-branch-name.outputs.branch }} to main"
          branch: ${{ steps.get-branch-name.outputs.branch }}  # Use the current branch for the PR
          base: "main"  # The branch you want to merge into
