name: On new branch to main

on:
  create

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: '07module/web-demo2'

jobs:
  new-branch-or-tag-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Validate terraform fmt
        run: terraform fmt -check
        working-directory: ${{ env.WORKING_DIR }}

      - name: Validate Terraform code
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}

  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

  create-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    needs: [new-branch-or-tag-job, tfsec]  # Ensure this job runs only if the previous jobs succeed
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Automated PR: Merge branch to main"
          branch: "auto-pr-branch"  # This will be the name of the branch for the PR
          base: "main"  # The branch you want to merge into
